version: '3'

services:
  web:
    env_file: .env   # Change env_sample.txt to env.txt
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    command: sh entrypoint.sh

  db:
    image: mdillon/postgis:11-alpine
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    # ports:
    #   - 5432:5432
    env_file:
      - pg_env.txt
