on:
  pull_request:
    branches:
      - master
      - develop
      - staging
  push:
    branches:
      - "*"
name: Code Check
jobs:
  build:
    name: Code Check
    runs-on: naxa2
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.9
    - name: Check Version
      run: python --version
    - name: PreCommit
      uses: pre-commit/action@v2.0.3
