on:
  push:
    tags:
      - '*'
name: Create a Release
jobs:
  build:
    name: Create release from tag
    runs-on: naxa2
    steps:
    - uses: actions/checkout@v1
    - name: Create a Releases (if tag:)
      uses: ncipollo/release-action@v1
      with:
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
